### ISSUE TITLE
address_ipvN is not deterministic

### ISSUE THREAD

**Issue by pdf** [jtopjian/terraform-provider-lxc#3]
The value for address outputs does not appear to be deterministic, so in a cycle of apply/destroy runs, the returned address may come from any interface.  This is a problem if one interface is publicly accessible but another is not.  I think the best way to deal with this might be to enumerate interfaces in order, so that configuration can determine the output result.

**Comment by pdf** [comment]
Hrm, unfortunately, it doesn't look like this is possible with the APIs exposed by `go-lxc` (see lxc/go-lxc#42).  Once we can get IPs by both interface and family, I'll send a PR that first queries `eth0`, then falls back to querying for any address, for each family.

**Comment by jtopjian** [comment]
> Hrm, unfortunately, it doesn't look like this is possible with the APIs exposed by go-lxc

Yup - but awesome that you sent in a PR :)

In addition to the generic `address_v4` and `address_v6`, we could also have an exported `interfaces` block that will enumerate all known NICs with their MAC and IP addresses.

**Comment by pdf** [comment]
I suppose that's easy enough to implement if the above PR makes it into upstream, so that people can choose which interface to connect on.  Though eth0 as the default address source is probably still sensible, since most platforms use that for routable addresses.  As it stands, terraform can't perform provisioning reliably because on multi-homed containers it will arbitrarily try to connect to an interface that may not be accessible from the host.

**Comment by jtopjian** [comment]
I agree with all.

The `interfaces` block would just be a bunch of exported information that may be useful to the user for local scripts or just informational purposes.

As an example from the OpenStack provider:

```
  network.# = 1
  network.0.fixed_ip_v4 = 10.1.1.24
  network.0.fixed_ip_v6 = [2600:fd00:4:1000:f816:3eff:fe73:f28]
  network.0.mac = fa:16:3e:73:0f:28
  network.0.name = mynetwork
  network.0.port = 
  network.0.uuid = c76b8a13-8530-4de9-adc0-18375e21900d
```

My idea was to do something similar, but replace `network` with `interface`.

And now that I think about it, each interface may have more than one IP, so this might be a bit more involved than I originally thought, so this all can go in another PR / issue.

**Comment by jtopjian** [comment]
Looks like your patch was merged. :smile: 

Here's some quick changes that allow an interface to be specified as the deterministic NIC:

https://github.com/jtopjian/terraform-provider-lxc/tree/specify-nic

Let me know if you have any comments.
